### ISSUE TITLE
rasterization strategies in zonalstats funcs

### ISSUE THREAD

**Issue by MatteoCorvi** [remotesensinginfo/rsgislib#50]
Hi,

is there one of the zonalstats.METHOD_* that when applied by zonalstats.image_zone_to_hdf would yield same extraction results as the the other zonalstats functions?

Lately I have been trying out the zonalstats functions to extract hdf5 datasets and zonalstats.image_zone_to_hdf in particular seems to be quite fast. However, compared to the other functions of the zonalstats module and a rasterstats based implementation I wrote myself, the rasterization strategy seems to yield different results in number of pxls returned no matter which one I pick among the zonalstats.METHOD_* available. 

The closest I got to the numbers returned by the other implementations is by setting 
pxl_in_poly_method=zonalstats.METHOD_POLYOVERLAPSORCONTAINSPIXEL
and then masking out nodata values extracted on a masked raster by the same function, but still a bit short (50 something pxls over 15k so probably no big deal, but still wondering why). This is for extracting rois from polygons distanced enough so I wasn't concerned about extracting pixels multiple times by adopting a more generous strategy.

There are a few quite small polygons (that with rasterstats and other rsgislib functions yield less than 5 pxls), but even when removing these there is still some difference in the dimension of the retrieved datasets.

**Comment by petebunting** [comment]
Hi, 

I think there is only one function which uses the zonalstats.METHOD_* option(rsgislib.zonalstats.image_zone_to_hdf) and this is a legacy function so I would suggest rasterising the vector layer and then using rsgislib.zonalstats.extract_zone_img_values_to_hdf. You will also have an image so if you want to know which pixels are selected then you’ll be able to see it. 

All the other main zonal stats function rsgislib.zonalstats.calc_zonal* use gdal_rasterize to selection pixels so rasterising the vector layer should produce the same pixel selection.

In terms of why you get different results for different selection options it will be because of the edge boundary cases, for example whether the centre of the pixel or the whole pixel is within the bounds of the polygon etc. depending on which option had been selected. I am not sure what criteria gdal_rasterize uses so can not therefore say which would be the closest to that. 

Best wishes, 

Pete

**Comment by MatteoCorvi** [comment]
Hi, thanks for replying.

Yes in the end I used the function you suggested implementing rasterization, I noticed it is actually faster with an higher number of polygons to extract.

All the best,
Matteo
